# Generated by Django 4.2.9 on 2024-03-13 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('product_name', models.CharField(max_length=512)),
                ('product_description', models.CharField(max_length=3000)),
                ('product_price', models.FloatField()),
                ('firebase_path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_expired', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512)),
                ('item', models.ManyToManyField(related_name='saved_items', to='shop.userlistings')),
            ],
        ),
    ]
