# Generated by Django 4.2.9 on 2024-03-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='is_renewed',
            field=models.BooleanField(default=False),
        ),
    ]
