# Generated by Django 4.2.9 on 2024-03-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userlistings_is_renewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwishlist',
            name='username',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.userlistings')),
            ],
        ),
    ]
