# Generated by Django 4.2.9 on 2024-03-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_userwishlist_username_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='num_buyers',
            field=models.IntegerField(default=0),
        ),
    ]
