# Generated by Django 4.2.9 on 2024-03-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userlistings_num_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
