# Generated by Django 4.2.9 on 2024-03-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='heading',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
