# Generated by Django 4.2.9 on 2024-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_usercomment_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='ratings',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
