# Generated by Django 4.2.9 on 2024-03-14 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_usercomment_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
