# Generated by Django 4.2.9 on 2024-03-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_usercomment_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlistings',
            old_name='num_buyers',
            new_name='num_raters',
        ),
    ]
