# Generated by Django 4.2.9 on 2024-03-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_num_buyers_userlistings_num_raters'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='num_orders',
            field=models.IntegerField(default=0),
        ),
    ]
