# Generated by Django 4.2.9 on 2024-03-15 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_userlistings_num_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=512)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
