# Generated by Django 4.2.9 on 2024-03-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(default='requested', max_length=20),
            preserve_default=False,
        ),
    ]
