# Generated by Django 4.2.9 on 2024-03-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_userorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
