# Generated by Django 4.2.9 on 2024-03-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_usernotification_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='task',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
