# Generated by Django 4.2.9 on 2024-03-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
