# Generated by Django 4.2.9 on 2024-03-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_userorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='ratings',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userlistings',
            name='firebase_path',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userlistings',
            name='product_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userlistings',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='body',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
