# Generated by Django 4.2.9 on 2024-03-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_usercomment_comment_alter_usercomment_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistings',
            name='ratings',
            field=models.FloatField(default=0, null=True),
        ),
    ]
