# Generated by Django 4.2.9 on 2024-03-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_userlistings_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(default=966578183580, max_length=15),
            preserve_default=False,
        ),
    ]
