# Generated by Django 4.2.9 on 2024-03-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_userprofile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
