# Generated by Django 4.2.9 on 2024-03-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_userprofile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='new_orders',
            field=models.IntegerField(default=0),
        ),
    ]
