# Generated by Django 4.2.9 on 2024-03-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_userlistings_new_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='whatsapp',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
