# Generated by Django 4.2.9 on 2024-03-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_userdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
