# Generated by Django 4.2.9 on 2024-03-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_fcmtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMToken',
        ),
    ]
