# Generated by Django 4.2.9 on 2024-03-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
