# Generated by Django 4.2.10 on 2024-03-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_fcmtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=255)),
                ('item', models.ManyToManyField(to='shop.userlistings')),
            ],
        ),
    ]
