# Generated by Django 4.2.10 on 2024-03-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistings',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
