# Generated by Django 4.2.10 on 2024-03-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_invoice_item_invoice_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.AddField(
            model_name='userlistings',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
