# Generated by Django 4.2.10 on 2024-03-31 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_remove_invoice_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
