# Generated by Django 4.2.10 on 2024-03-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=255)),
            ],
        ),
    ]
