# Generated by Django 4.2.10 on 2024-03-31 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.userlistings'),
            preserve_default=False,
        ),
    ]
