# Generated by Django 4.2.10 on 2024-04-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistings',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
