# Generated by Django 4.2.10 on 2024-04-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_userlistings_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
