# Generated by Django 4.2.10 on 2024-04-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_croppingimagecoordinatescache'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privileged',
            field=models.BooleanField(default=False),
        ),
    ]
