# Generated by Django 4.2.10 on 2024-04-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_userprofile_privileged'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
