# Generated by Django 4.2.10 on 2024-04-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_userlistings_num_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='building_code',
            field=models.CharField(default='yeah', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_no',
            field=models.CharField(default='yeah', max_length=10),
        ),
    ]
