# Generated by Django 4.2.10 on 2024-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_remove_userprofile_address_userprofile_building_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='building_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
