# Generated by Django 4.2.10 on 2024-04-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_userprofile_building_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='address',
        ),
        migrations.AddField(
            model_name='userorder',
            name='building_code',
            field=models.CharField(default='yeah', max_length=5),
        ),
        migrations.AddField(
            model_name='userorder',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
    ]
