# Generated by Django 4.2.10 on 2024-04-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_remove_userorder_address_userorder_building_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDemands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('request', models.CharField(max_length=64)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
