# Generated by Django 4.2.10 on 2024-05-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_userdemands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDemands',
        ),
    ]
