# Generated by Django 4.2.10 on 2024-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_delete_userdemands'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('first_vist', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=128)),
                ('button_text', models.CharField(default='Okay', max_length=16)),
            ],
        ),
    ]
