# Generated by Django 4.2.10 on 2024-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_usernotices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotices',
            name='first_vist',
        ),
        migrations.AddField(
            model_name='usernotices',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_sellnewproduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
