# Generated by Django 4.2.10 on 2024-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_remove_usernotices_first_vist_usernotices_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('visited_home', models.BooleanField(default=False)),
                ('visited_shop', models.BooleanField(default=False)),
                ('visited_orders', models.BooleanField(default=False)),
                ('visited_wishlist', models.BooleanField(default=False)),
                ('visited_sellnewproduct', models.BooleanField(default=False)),
                ('visited_notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visited_home',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visited_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visited_orders',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visited_sellnewproduct',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visited_shop',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visited_wishlist',
        ),
    ]
