# Generated by Django 4.2.10 on 2024-05-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_firstvisits_remove_userprofile_visited_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstvisits',
            name='visited_notifications',
        ),
        migrations.RemoveField(
            model_name='firstvisits',
            name='visited_sellnewproduct',
        ),
    ]
