# Generated by Django 4.2.10 on 2024-05-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_remove_firstvisits_visited_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotices',
            name='seen',
        ),
        migrations.AddField(
            model_name='usernotices',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
