# Generated by Django 4.2.10 on 2024-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_remove_userlistings_is_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='in_developers_pick',
            field=models.BooleanField(default=False),
        ),
    ]
