# Generated by Django 4.2.10 on 2024-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_userlistings_in_developers_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fav_tags',
            field=models.CharField(default='', max_length=512),
        ),
    ]
