# Generated by Django 4.2.10 on 2024-05-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_userprofile_fav_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fav_tags',
            field=models.CharField(default='everything', max_length=512, null=True),
        ),
    ]
