# Generated by Django 4.2.10 on 2024-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_alter_userprofile_fav_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
