# Generated by Django 4.2.10 on 2024-05-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_userlistings_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistings',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
