# Generated by Django 4.2.10 on 2024-05-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_userlistings_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlistings',
            name='quantity',
        ),
        migrations.AddField(
            model_name='userorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
