# Generated by Django 4.2.10 on 2024-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_remove_userlistings_quantity_userorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='additional_description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
